CREATE TABLE IF NOT EXISTS enterprise_auth_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(32) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  allow_local_fallback BOOLEAN NOT NULL DEFAULT TRUE,
  sync_role BOOLEAN NOT NULL DEFAULT FALSE,
  ldap_host VARCHAR(255) NOT NULL DEFAULT '',
  ldap_port INT NOT NULL DEFAULT 389,
  ldap_use_tls BOOLEAN NOT NULL DEFAULT FALSE,
  ldap_start_tls BOOLEAN NOT NULL DEFAULT FALSE,
  ldap_skip_tls_verify BOOLEAN NOT NULL DEFAULT FALSE,
  ldap_tls_ca_file VARCHAR(1000) NOT NULL DEFAULT '',
  ldap_tls_server_name VARCHAR(255) NOT NULL DEFAULT '',
  ldap_bind_dn VARCHAR(500) NOT NULL DEFAULT '',
  ldap_bind_password_ciphertext TEXT NULL,
  ldap_base_dn VARCHAR(500) NOT NULL DEFAULT '',
  ldap_user_filter VARCHAR(1000) NOT NULL DEFAULT '(&(objectClass=person)(uid=%s))',
  ldap_username_attribute VARCHAR(100) NOT NULL DEFAULT 'uid',
  ldap_email_attribute VARCHAR(100) NOT NULL DEFAULT 'mail',
  ldap_group_base_dn VARCHAR(500) NOT NULL DEFAULT '',
  ldap_group_filter VARCHAR(1000) NOT NULL DEFAULT '(member=%s)',
  ldap_admin_group_dns TEXT NULL,
  ldap_default_role VARCHAR(32) NOT NULL DEFAULT 'user',
  version BIGINT NOT NULL DEFAULT 1,
  updated_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_enterprise_auth_settings_provider (provider),
  INDEX idx_enterprise_auth_settings_version (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
